version: '3.8'
services:
  emre-db:
    image: postgres:13
    ports:
      - 4343:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - emrets
networks:
  emrets: